# Config
rss: /atom.xml           # link
# favicon: /images/favicon.png # Hexo's favicon_tag lacks the flexibility to supply different sizes of favicon
json_id_favicon: /images/favicon-200.png
blog_logo:
header_image: https://cdn.nanke.suste.ch/img/nanke-assets/nanke-banner-2020-04.svg
bio: 在这里，读懂南科
post_toc: true

# Keywords
keywords: hexo, casper, ghost, theme

# Menu
menu:
  快讯网: https://news.nanke.suste.ch/
  即时新闻: /categories/即时新闻
  深度: /categories/深度
  关于本站: /about
  全部文章: /archives

  # you can add here

# author
author_image:   # link
author_bio:
author_location:

# Social Links
social:
  weibo:
  github: https://github.com/nankeyilu
  twitter:
  facebook:
  telegram: https://t.me/s/nankeyilu
  bilibili:
  youtube:
  # You only can use that I have added, I will keep adding

# Footer Links
footer_text:
  # title: link
  # 粤ICP备xxxxxxx号-x: http://www.miitbeian.gov.cn
  # 粤公网安备xxxxxxx号: http://www.beian.gov.cn

# Widget
widgets:
  recent_posts: true
  category: true
  tagcloud: true
  # This is a simple theme, I think 3 is enough.

# Post page fload header
floadheader: false

# Gallery
# https://github.com/dimsemenov/PhotoSwipe
photoswipe: true

# LazyLoad
# home page has enabled, this value is to post page
# https://github.com/dinbror/blazy
lazyload: false

# Local Search
local_search: true

# Comment
# https://valine.js.org
comment: true
valine:
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: true # Verification code
  appId: 2YTtGBClfFU6JoO8D95qlCJq-MdYXbMMI # your leancloud application appid
  appKey: VCyC8V6cmFNCRzgPoD0K7vpt # your leancloud application appkey
  placeholder: 想说点啥？(提示：昵称，邮箱，网址均非必填项。您可以选择匿名评论，但请对自己的言论负责。) # comment box placeholder
  pageSize: 10 # pagination size
  avatar: mm # gravatar style
  visitor: true # page view record

# PWA
# you need create a manifest.json file in hexo's source folder
manifest: true
service_workers: false

navColor: '6b98c0'

# Baidu Push
baidu: false

# Google Analytics
googleAnalytics: true
GA_TRACKING_ID: UA-160296007-1

ellipsis: ...
